# Generated by Django 2.2.7 on 2019-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('itemNumber', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('vendor', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('onHand', models.IntegerField()),
                ('price', models.CharField(max_length=16)),
                ('sex', models.CharField(max_length=32)),
                ('style', models.CharField(max_length=32)),
                ('size', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=32)),
                ('itemNumber', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('vendor', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('numberSold', models.IntegerField()),
                ('unitPrice', models.FloatField()),
                ('sellPrice', models.FloatField()),
                ('sex', models.CharField(max_length=32)),
                ('style', models.CharField(max_length=32)),
                ('size', models.CharField(max_length=32)),
            ],
        ),
    ]
