# Generated by Django 2.2.7 on 2019-11-21 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='name',
            new_name='itemName',
        ),
        migrations.RenameField(
            model_name='salesreport',
            old_name='name',
            new_name='itemName',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='onHand',
        ),
        migrations.AddField(
            model_name='inventory',
            name='onHandCollege',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='onHandSolano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='width',
            field=models.CharField(default='NA', max_length=32),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='dateSold',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='width',
            field=models.CharField(default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='style',
            field=models.CharField(default='normal', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='style',
            field=models.CharField(default='normal', max_length=32),
        ),
    ]
