# Generated by Django 2.2.7 on 2019-11-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_auto_20191121_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='salesreport',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='inventory',
            name='subCategory',
            field=models.CharField(default=' ', max_length=32),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='subCategory',
            field=models.CharField(default=' ', max_length=32),
        ),
    ]
