# Generated by Django 2.2.6 on 2019-11-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=32)),
                ('name', models.CharField(default='null', max_length=64)),
                ('phone', models.CharField(default='000-000-0000', max_length=16)),
                ('type', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('subcategory', models.CharField(default='none', max_length=64)),
                ('vendor', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('width', models.CharField(blank=True, max_length=64)),
                ('item_number', models.CharField(blank=True, max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='open', max_length=64)),
                ('requested_by', models.CharField(max_length=64)),
                ('purchase_order', models.CharField(blank=True, max_length=64)),
                ('quantity', models.CharField(
                    blank=True, default='0', max_length=12)),
                ('other_store_inventory', models.BooleanField(default=False)),
                ('hold_until', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('request', models.ForeignKey(on_delete='PROTECT',
                                              related_name='notes', to='manager_engine.Request')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='admin', max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('request', models.ForeignKey(on_delete='PROTECT',
                                              related_name='histories', to='manager_engine.Request')),
            ],
        ),
    ]
