# Generated by Django 2.2.6 on 2019-11-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='hold_until',
            field=models.DateField(auto_now_add=True),
        ),
    ]
